Add a section on setting up the OBS Virtual Camera
getsolus/help-center-docs pull request #299
Opened 2021-09-17 16:04 UTC by sheepman4267

## Description

This adds instructions for installing v4l2loopback to enable the OBS Virtual Camera.

### Submitter Checklist

- [x ] Updated the "lastmod" portion at the top of any modified Markdown files.
- [ ] Squashed commits with `git rebase -i` (if needed) - only made one commit

2021-09-17 17:12 UTC, JoshStrobl requested changes

2021-09-17 17:12 UTC, JoshStrobl commented on software/open-broadcaster-software/en.md
> +```
Can be condensed a bit.

```
This should return a version which ends in `.current` or `.lts`.

- If you are running the "current" kernel, install `v4l2loopback-current`: `sudo eopkg install v4l2loopback-current`
- If you are running the "lts" kernel, install `v4l2loopback`: `sudo eopkg install v4l2loopback`
```

2021-09-17 17:12 UTC, JoshStrobl commented on software/open-broadcaster-software/en.md
> +OBS includes a virtual webcam device which can be used to send your OBS stream to video conferencing programs. In order to use this on Solus, you must install `v4l2loopback`. There are two versions o
Let's change the following:

```
In order to use this on Solus, you must install `v4l2loopback`. There are two versions of `v4l2loopback` available in the repository, and you must choose the version that corresponds to the kernel you have installed.
```

To...

```
In order to use this on Solus, you must first install from our repository a separate kernel module that is responsible for creating the necessary "loopback" device. There are two versions of this software available in the repository, you must choose the version that corresponds to the kernel you have installed.
```

The reason for this is some folks will just immediately install the first package name they see and not read any further, so we should just avoid using it until we provide the respective instructions.

2021-10-04 10:26 UTC, JoshStrobl commented
@sheepman4267 Any plans to address this?

2021-10-05 03:04 UTC, sheepman4267 commented
@JoshStrobl Edits complete, thank you for the feedback!

2021-10-05 03:37 UTC, JoshStrobl commented
LGTM, thanks!

2021-10-05 03:37 UTC, merged