Add page for changing the eopkg configuration
getsolus/help-center-docs pull request #337
Opened 2023-05-29 20:08 UTC by EbonJaeger

## Description

This adds a page detailing how to modify the default eopkg configuration.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)

2023-06-01 10:08 UTC, JoshStrobl requested changes

2023-06-01 10:08 UTC, JoshStrobl commented on docs/packaging/eopkg-configuration.md
> +Most keys in the config you'll probably want to leave untouched. Some, however, are useful to know about:
```suggestion
Most keys in the config you'll probably want to leave untouched. However, some are useful to know about:
```

2023-06-01 10:08 UTC, JoshStrobl commented on docs/packaging/eopkg-configuration.md
> +# Modifying the Eopkg Configuration
```suggestion
# Eopkg Configuration
```

2023-06-24 15:54 UTC, davidjharder commented
Josh: You want to merge this? Alternatively I can

2023-06-29 18:37 UTC, merged