docs/editions: Replace categories view with feature rich page
getsolus/help-center-docs pull request #342
Opened 2023-06-23 15:34 UTC by joebonrichie

## Description

This replaces the categories view with a feature rich page for the editions/spins. It includes screenshots, a short description as well as direct links to the configuration and tips and tricks sub pages; all contained within a nice card view format.

A dependency is added on @docusaurus/plugin-ideal-image for automatic image resizing at deploy time.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)

2023-06-29 18:40 UTC, JoshStrobl requested changes

2023-06-29 18:40 UTC, JoshStrobl commented on src/components/editions/index.tsx
> +		image: require('@site/static/img/Budgie.jpg'),
Should be doing an import instead of require.

2023-06-29 18:40 UTC, JoshStrobl commented on src/components/editions/index.tsx
> +		image: require('@site/static/img/Plasma.jpg'),
Should be doing an import instead of require.

2023-06-29 18:40 UTC, JoshStrobl commented on src/components/editions/index.tsx
> +		image: require('@site/static/img/GNOME.jpg'),
Should be doing an import instead of require.

2023-06-29 18:40 UTC, JoshStrobl commented on src/components/editions/index.tsx
> +		image: require('@site/static/img/MATE.jpg'),
Should be doing an import instead of require.

2023-06-29 18:40 UTC, JoshStrobl commented on src/components/editions/index.tsx
> +		</div>
Indentation needs fixing, should be using translatables here, don't use div use Box from MUI, prefer MUI Button and Button Group, etc.

2023-06-29 18:40 UTC, JoshStrobl commented on src/components/editions/index.tsx
> +		<div className="row">
If we're doing a grid, this should be a GridItem and use Unstable_Grid from MUI. If we're doing a vertical list, use a Stack.

2023-06-29 18:45 UTC, JoshStrobl commented on src/components/editions/index.tsx
> +interface Props {
Should not be interface, use `type` e.g. `type EditionCardProps = {`

2023-06-29 18:45 UTC, JoshStrobl commented on src/components/editions/index.tsx
> +function EditionCard({name, image, url, urlConfig, urlTips, description}: Props) {
So not use function, do: `const EditionCard = ({ ... }: EditionCardProps) => {`

2023-06-29 18:45 UTC, JoshStrobl commented on src/components/editions/index.tsx
> +export function EditionCardsRow(): JSX.Element {
Do not use function, use `const` arrow funcs. You also don't need to specify that it is a JSX.Element if you use the right elements.

2023-06-29 18:46 UTC, JoshStrobl commented
Please be sure to use `yarn prettier` as well.

2023-06-30 19:32 UTC, joebonrichie commented
Didn't end up using MUI buttons as I can't say I liked the look of them

2023-06-30 21:45 UTC, joebonrichie commented
Use MUI Buttons

2023-07-07 20:24 UTC, JoshStrobl approved these changes
LGTM :rocket:

2023-07-07 20:24 UTC, merged