Add draft privacy policy
getsolus/help-center-docs pull request #357
Opened 2023-07-12 20:44 UTC by davidjharder

## Description

Add a privacy policy. *This is a draft*

Resolves #158

### Submitter Checklist

- [x] Squashed commits with `git rebase -i` (if needed)

2023-10-01 14:06 UTC, silkeh requested changes
Generally looks good, clear and to the point!

2023-10-01 14:06 UTC, silkeh commented on docs/user/privacy.md
> +If you are covered by the [GDPR](https://gdpr.eu/) you have rights as a data subject. Your rights are detailed under [Chapter 3 of the GDPR](https://gdpr.eu/article-12-how-controllers-should-provide-
I feel like there should be a more user-friendly link for this, but I wasn't able to quickly find one from an EU website :disappointed:

2023-10-01 14:32 UTC, davidjharder commented on docs/user/privacy.md
> +- Some packages may include their own built-in telemetry (examples: Firefox, Steam). Solus cannot control data collected in this way. These packages may allow you to disable this telemetry.
What we do to individual packages does not change this wording unless we are certain we have disabled all telemetry everywhere. Maybe this is a good goal, but for now this wording is accurate

2023-10-01 15:36 UTC, davidjharder commented on docs/user/privacy.md
> +- `discuss.getsol.us`
done

2023-10-01 23:06 UTC, EbonJaeger requested changes
Just one minor thing.

2023-10-01 23:06 UTC, EbonJaeger commented on docs/user/privacy.md
> +# Privacy Policy  (Draft)
Might want to remove that before merging :P

```suggestion
# Privacy Policy
```

2023-10-01 23:21 UTC, davidjharder commented on docs/user/privacy.md
> +Any concerns or requests about personal data should be sent to [privacy@getsol.us](mailto:privacy@getsol.us) TODO: what is the correct email?
Also, this is draft language still

2023-10-11 15:00 UTC, silkeh commented on docs/user/privacy.md
> +If you are covered by the [GDPR](https://gdpr.eu/) you have rights as a data subject. Your rights are detailed under [Chapter 3 of the GDPR](https://gdpr.eu/article-12-how-controllers-should-provide-
```suggestion
If you are covered by the [GDPR](https://gdpr.eu/) you have rights as a data subject. Your rights are detailed under [Chapter 3 of the GDPR](https://gdpr.eu/article-12-how-controllers-should-provide-personal-data-to-the-subject/). Additionally, you have the right to lodge a complaint with your national [Data Protection Authority](https://edpb.europa.eu/about-edpb/board/members_en).
```

2023-10-11 15:03 UTC, silkeh approved these changes

2023-10-11 15:06 UTC, EbonJaeger approved these changes
LGTM, thanks! :)

2023-10-11 15:06 UTC, merged