General update for phab -> GH migration
getsolus/help-center-docs pull request #371
Opened 2023-08-22 02:25 UTC by davidjharder

- Generally update references and surrounding word-salad wherever we use dev.getsol.us
- Additionally create references to issues.getsol.us
- Assumptions:
  - `dev.getsol.us` will point to package repos (and eventually, the package monorepo) 
    - AKA "Packages"
  - `issues.getsol.us` will point to a general bug report landing page, not a specific form
    - AKA "Issue Tracker" or "Main Solus GitHub Issue Tracker" when contrasting with various other GH issue trackers
- TODO: Actually set up DNS for issues.getsol.us

2023-08-22 02:26 UTC, davidjharder commented
Marking this as draft until people weigh in on the `issues.getsol.us` idea, and the DNS entry is created

2023-08-24 18:59 UTC, TraceyC77 commented
I really like having human friendly domains for issues.getsol.us and dev.getsol.us (which might be better as packages.getsol.us) that point to the current repos. This makes it much easier for users to remember those links and for us to share them.

We might also want one for issues.budgie...something since those are in a separate repo, but that's not part of this PR. Just mentioning the idea.

2023-08-24 19:56 UTC, davidjharder commented
`packages.getsol.us` is taken (e.g. https://packages.getsol.us/shannon/)
So if we wanted to use something slightly more intuitive than `dev`, maybe `repo`?
But part of the reasoning with keeping `dev` is that old links will get people roughly to roughly the right place. For instance: this old link to the 4.5 ISO task https://dev.getsol.us/T10476

2023-08-24 19:59 UTC, TraceyC77 commented
****

> `packages.getsol.us` is taken (e.g. https://packages.getsol.us/shannon/) So if we wanted to use something slightly more intuitive than `dev`, maybe `repo`? But part of the reasoning with keeping `dev` is that old links will get people roughly to roughly the right place. For instance: this old link to the 4.5 ISO task https://dev.getsol.us/T10476

With that, I say we keep using dev.getsol.us

2023-08-24 20:05 UTC, TraceyC77 requested changes

2023-08-24 20:05 UTC, TraceyC77 commented on docs/packaging/submitting-a-package.md
> +If you forked github.com/solus-packages/nano. It would be forked to `github.com/mygithubaccount/nano`. You can then set the push url to
The first sentence is a fragment. Recommend:
If you forked github.com/solus-packages/nano, it would be ...

2023-08-24 20:05 UTC, TraceyC77 commented on docs/user/software/command-line/index.md
> +fonts `powerline-fonts`. Both are available in the Software Center or via `eopkg`` in a terminal:
There's an extra backtick after eopkg

2023-08-24 20:26 UTC, davidjharder commented
Fixed Tracey's items, Also changed to use GH style references for task linking: `Depends on T123` -> `Depends on #123`

2023-08-24 20:54 UTC, TraceyC77 approved these changes
LGTM

2023-08-25 22:25 UTC, merged