Monorepo docs
getsolus/help-center-docs pull request #375
Opened 2023-09-17 14:08 UTC by silkeh

## Description

- Update the docs for working with a monorepo.
- Replace `make` by `go-task`.

Depends on #373

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)

2023-09-17 19:57 UTC, Staudey reviewed
The default branch of getsolus/packages is now `main`, unless that is supposed to change

2023-09-17 19:57 UTC, Staudey commented on docs/packaging/git-basics.md
> +Run `git fetch`, and `git rebase origin/master` to pull the changes in.
```suggestion
Run `git fetch`, and `git rebase origin/main` to pull the changes in.
```

2023-09-17 19:57 UTC, Staudey commented on docs/packaging/git-basics.md
> +You can check your branch against master with `git diff origin/master..my-branch`.
```suggestion
You can check your branch against main with `git diff origin/main..my-branch`.
```

2023-09-17 19:57 UTC, Staudey commented on docs/packaging/git-basics.md
> +git switch master
```suggestion
git switch main
```

2023-09-17 19:57 UTC, Staudey commented on docs/packaging/creating-a-new-package.md
> +If you already have a fork of [getsolus/packages](https://github.com/getsolus/packages) in GitHub, log into GitHub. Make sure you're looking at the master branch. Check to see that your fork is up to
```suggestion
If you already have a fork of [getsolus/packages](https://github.com/getsolus/packages) in GitHub, log into GitHub. Make sure you're looking at the main branch. Check to see that your fork is up to date with the main repo it was forked from. If your fork indicates it is behind, use the "Sync fork" button to bring it up to date.
```

2023-09-17 19:57 UTC, Staudey commented on docs/packaging/creating-a-new-package.md
> +git switch master
```suggestion
git switch main
```

2023-09-17 19:57 UTC, Staudey commented on docs/packaging/git-basics.md
> +## Keeping your branch up to date with the master branch
```suggestion
## Keeping your branch up to date with the main branch
```

2023-09-17 19:57 UTC, Staudey commented on docs/packaging/git-basics.md
> +Run `git fetch`, and `git rebase origin/master` to pull the changes in.
```suggestion
Run `git fetch`, and `git rebase origin/main` to pull the changes in.
```

2023-09-17 19:57 UTC, Staudey commented on docs/packaging/git-basics.md
> +First, change to the package directory, switch to the master branch, then delete your local and the remote branches.
```suggestion
First, change to the package directory, switch to the main branch, then delete your local and the remote branches.
```

2023-09-17 19:57 UTC, Staudey commented on docs/packaging/updating-an-existing-package.md
> +If you already have a fork of [getsolus/packages](https://github.com/getsolus/packages) in GitHub, log into GitHub. Make sure you're looking at the master branch. Check to see that your fork is up to
```suggestion
If you already have a fork of [getsolus/packages](https://github.com/getsolus/packages) in GitHub, log into GitHub. Make sure you're looking at the main branch. Check to see that your fork is up to date with the main repo it was forked from. If your fork indicates it is behind, use the "Sync fork" button to bring it up to date.
```

2023-09-17 21:15 UTC, silkeh commented
@Staudey: good catch. Thanks!

2023-09-18 22:23 UTC, TraceyC77 requested changes
Just a few updates needed, then this is good to go. Good work overall.

2023-09-18 22:23 UTC, TraceyC77 commented on docs/packaging/prepare-for-packaging.mdx
The "Setting up a Build Directory" section needs to be updated. If you follow it as is you will wind up with two folders for `common`

```
~/solus-builds/common
~/solus-builds/packages/common
```

The symlink commands also need to be updated to point to `~/solus-builds/packages/common`
The packaging folder layout also needs to be updated.

2023-09-18 22:23 UTC, TraceyC77 commented on docs/packaging/updating-an-existing-package.md
On the previous line 
"If you do not yet have a clone of the package..."

should be
"If you do not yet have a clone of your packages repo fork, change to your packaging directory and clone your fork. Then, switch to the  directory of the package to update. For example:"

2023-09-18 22:23 UTC, TraceyC77 commented on docs/packaging/updating-an-existing-package.md
>  cd ~/solus-builds/package-name
This needs to be udpated

```suggestion
cd ~/solus-builds/packages/packages/n/nano
```

2023-09-18 22:55 UTC, EbonJaeger requested changes
Very good, overall!

2023-09-18 22:55 UTC, EbonJaeger commented on docs/packaging/creating-a-new-package.md
> +If you already have a fork of [getsolus/packages](https://github.com/getsolus/packages) in GitHub, log into GitHub. Make sure you're looking at the main branch. Check to see that your fork is up to d
Thinking the name of the branch should be made clear that it isn't just a word in the sentence.
```suggestion
If you already have a fork of [getsolus/packages](https://github.com/getsolus/packages) in GitHub, log into GitHub. Make sure you're looking at the `main` branch. Check to see that your fork is up to date with the main repo it was forked from. If your fork indicates it is behind, use the "Sync fork" button to bring it up to date.
```

2023-09-18 22:55 UTC, EbonJaeger commented on docs/packaging/updating-an-existing-package.md
> +If you already have a fork of [getsolus/packages](https://github.com/getsolus/packages) in GitHub, log into GitHub. Make sure you're looking at the main branch. Check to see that your fork is up to d
Same as above.
```suggestion
If you already have a fork of [getsolus/packages](https://github.com/getsolus/packages) in GitHub, log into GitHub. Make sure you're looking at the `main` branch. Check to see that your fork is up to date with the main repo it was forked from. If your fork indicates it is behind, use the "Sync fork" button to bring it up to date.
```

2023-09-19 18:20 UTC, silkeh commented on docs/packaging/prepare-for-packaging.mdx
>  ```bash
I removed the `system.devel` component entirely, and just added `ypkg` separately.

2023-09-19 18:22 UTC, silkeh commented on docs/packaging/prepare-for-packaging.mdx
>  Namely:
I merged the two lists, so it should be clearer now.

2023-09-19 18:32 UTC, EbonJaeger approved these changes
LGTM, thanks! :)

2023-09-19 23:44 UTC, TraceyC77 approved these changes
LGTM. Great work.

2023-09-19 23:56 UTC, merged