ROCm/HIP
getsolus/help-center-docs pull request #452
Opened 2024-01-13 19:46 UTC by GZGavinZhao

## Description

Adds a section about how to use software that runs on or interacts with ROCm/HIP.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)

2024-01-13 22:28 UTC, davidjharder commented
When this is ready for review, would you mind rebasing? I want a guinea pig for the new Github Actions

2024-01-14 00:51 UTC, GZGavinZhao commented
@davidjharder Since this is change is pretty easy to rebase, feel free to ping me on Matrix if you need me to do it a few more times.

2024-01-14 02:52 UTC, davidjharder commented
Rebase now and the checks should work as expected

2024-01-19 01:10 UTC, davidjharder commented
Hey, can you rebase this again to try the check

2024-01-19 01:24 UTC, GZGavinZhao commented
@davidjharder Done.

2024-01-23 00:55 UTC, deoxys94 requested changes

2024-01-23 00:55 UTC, deoxys94 commented on docs/user/software/development/rocm.md
> +ROCm is designed such that in order for a library to support N different GPU
This is a [wall of text](https://developers.google.com/style/accessibility#ease-of-reading), nobody will read this. 

With that being said, is it even necessary to mention all of this? I mean, for end users what matters is whether the GPU architecture is supported or not: If it's supported, they'll continue their day without reading everything; if it's not supported, they'll reach out using the available support channels.

```suggestion

:::tip

Install and run `rocminfo`  to see your GPU architecture.

:::

The ROCm package included in Solus supports the following GPU architectures out of the box:

- `gfx803`
- `gfx900`
- `gfx906`
- `gfx908`
- `gfx90a`
- `gfx1010`. This architecture can run programs compiled for `gfx101*` GPUs such as `gfx1011` and `gfx1012`, see [Emulating
  as a Supported Architecture](#emulating-as-a-supported-architecture).
- `gfx1030`. This architecture can run programs compiled for `gfx103*` GPUs such as `gfx1031` and `gfx1032`, see [Emulating
  as a Supported Architecture](#emulating-as-a-supported-architecture).
- `gfx1010`
- `gfx1011`
- `gfx1012`

If your GPU is not on the list, please open an issue in our [issue tracker](https://github.com/getsolus/packages/issues/new/choose) with your GPU model and release year.

This list is only the minimum supported architectures. Some packages like [Blender](#blender) support more architectures.
```

2024-01-23 00:55 UTC, deoxys94 commented on docs/user/software/development/rocm.md
> +:::tip
Move this note to the top of the section (See my first comment for more info)

2024-01-23 00:55 UTC, deoxys94 commented on docs/user/software/development/rocm.md
> +:::note
This shouldn't be a note (See my first comment for more info)

2024-01-23 00:55 UTC, deoxys94 commented on docs/user/software/development/rocm.md
> +If your GPU model is not on the list, please open an issue in
Move this right after the GPU list.

2024-01-23 00:55 UTC, deoxys94 commented on docs/user/software/development/rocm.md
> +
Add an introductory sentence to this block:

```suggestion
To install ROCm, execute the following command:
```

2024-01-23 00:55 UTC, deoxys94 commented on docs/user/software/development/rocm.md
> +almost identical (if not exactly identical) ISA that allows a program compiled for
Simplify this line:
```suggestion
similar ISAs. This allows programs compiled for
```

2024-01-23 00:55 UTC, deoxys94 commented on docs/user/software/development/rocm.md
> +one architecture to run seamlessly on other.
[Avoid excessive claims](https://developers.google.com/style/excessive-claims)
```suggestion
one architecture to run on another. 
```

2024-01-23 00:55 UTC, deoxys94 commented on docs/user/software/development/rocm.md
> +To emulate your GPU as a supported architecture, the environment variable
[Avoid passive voice](https://developers.google.com/style/voice):

```suggestion
To emulate your GPU as a supported architecture, add the `HSA_OVERRIDE_GFX_VERSION` environment variable to your system. For example:
```

2024-01-23 00:55 UTC, deoxys94 commented on docs/user/software/development/rocm.md
> +the `gfx1031` and `gfx1032` architectures. A list of such architectures is
In general, it's not a good idea to say things like "the previous section" or "the previous step". Instead, refer to the specific section name and include a link to it.

```suggestion
the `gfx1031` and `gfx1032` architectures. See the _Supported Hardware and GPU Architectures_ list for the supported architectures.
```

2024-01-24 12:00 UTC, GZGavinZhao commented
@deoxys94 Thank you so much for your detailed review! I will address them later in the week.

2024-01-26 19:31 UTC, davidjharder commented on docs/user/software/development/rocm.md
> +use GPU-acclerated rendering. These are more on the driver side of things and
```suggestion
use GPU-accelerated rendering. These are more on the driver side of things and 
```
Other than this, spelling checks out

2025-06-15 18:37 UTC, TraceyC77 commented
Hey Gavin. It's been quite a while since this was updated. Did you get a chance to respond to the reviews?

2025-06-17 04:02 UTC, GZGavinZhao commented
Oops sorry I forgot about this. Let me finish it up this weekend!

2025-06-23 04:47 UTC, GZGavinZhao commented
Hmmm I realize a lot has changed since I've written this and it will need another change when we update to ROCm v6.4, so I'll open a new PR when I update the ROCm stack to 6.4.

2025-06-23 04:47 UTC, closed without merging