Desktop Icons and Workspaces updates
getsolus/help-center-docs pull request #457
Opened 2024-01-16 18:17 UTC by johnandmegh

## Description

I tried to use some tips on Stack Overflow to "squash" the GitHub commits on my own this time...and somehow I think I made it even messier? (I don't think the end result is changed, but please let me know if I need to go back to the drawing board on how this is submitted)

Also, if this style of update is OK, I could probably tackle the rest of that page - I'm new all of Solus and Budgie, but it seems like a few different settings-related functions got moved from being accessed via Raven to being accessed via the Budgie Menu > Settings? Those would seem easy enough for me to grab new screenshots for and update wording.

Thanks,

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)

2024-01-16 19:06 UTC, davidjharder commented
Git workflow stuff: 
- In this particular case, the mess is fine because I can squash it.
- Are you using the github desktop client, the command line, or something else?
- I would encourage you to experiment with grouping multiple changes onto a commit
- "squashing" commits is actually using the `rebase`  command to organize a pile of commits in a certain way. The most concise explanation I've found is here https://docs.github.com/en/get-started/using-git/about-git-rebase
- For a more general git resource try https://git-scm.com/book/en/v2

Style:
- The style seems fine. In my opinion It's more important to update these rather old pages
- If you *do* want to take a deep dive into style, we recently published a style guide. Note that we haven't used it much yet https://help.getsol.us/docs/user/contributing/style

I'll review the content of your changes some time later; I wanted to respond to your questions first.

2024-01-16 20:17 UTC, johnandmegh commented
Thanks very much for the links, I will dig in!

2024-01-16 21:53 UTC, davidjharder commented
Yes, almost every guide and doc will assume you are using the cli on a cloned local repo, pushing to some remote like Github.

Many modern editors are git-aware out of the box. For example, if you use vscode, it has a "source control" tab that will do simple git operations for you.

I use the Github editing tools for small one-off edits. As soon as you are editing more than one file, or organizing commits in any way, you will have to get comfortable with the cli

2024-01-16 22:30 UTC, davidjharder commented
I should add: If you are struggling with something you can always ask for help in the Packaging or Development chat.

2024-01-17 04:21 UTC, davidjharder requested changes

2024-01-17 04:21 UTC, davidjharder commented on docs/user/editions/budgie/configuration.md
> +Desktop Icons are enabled by default when Budgie is installed for the first time. To check or toggle this setting, open the Budgie Desktop Settings app by selecting "Budgie Desktop Settings" from the
"..enabled by default when Budgie is installed for the first time." is redundant. I would suggest something like:
Desktop Icons are enabled by default. To disable them, open...

2024-01-17 04:21 UTC, davidjharder commented on docs/user/editions/budgie/configuration.md
> +Budgie enables the switching of workspaces via the Workspace Switcher. You can enable workspaces in Budgie by adding the Workspace Switcher applet to your panel.
via -> with 
"with" is simpler

2024-01-17 04:21 UTC, davidjharder commented on docs/user/editions/budgie/configuration.md
> +Click the + button next to 'Add applet' on the right side of the window. This will open the list of available applets - scroll down until you find `Workspace Switcher`, select it, and then click the
use quotes around "Workspace Switcher".
Backticks are reserved for package names, code, text entry, and so on

2024-01-17 04:21 UTC, davidjharder commented on docs/user/editions/budgie/configuration.md
> +To view these shortcuts, open the Budgie Control Center app, choose the Keyboard section in the left-hand sidebar, then scroll down in the right part of the window to choose 'Keyboard Shortcuts'.
Add quotes around "Keyboard" and change single quotes to double quotes around "Keyboard Shortcuts"

2024-01-17 04:21 UTC, davidjharder commented on docs/user/editions/budgie/configuration.md
> +Workspace shortcuts are contained in the 'Navigation' section of the Keyboard Shortcuts window.
Single to double quotes again

2024-01-17 04:21 UTC, davidjharder commented on docs/user/editions/budgie/configuration.md
> +There are 4 workspaces available in Budgie by default. To add a new workspace, click on the `+` button.
For consistency, change the backticks to double quotes. Even though the backticked version kind of looks like a button

2024-01-17 04:32 UTC, johnandmegh commented
Thanks! I think I addressed the wording/consistency issues that you mentioned, and I scanned for similar quotation mark issues in at least the portion included in this request - I'll check the other one I sent as well.

2024-01-17 14:12 UTC, davidjharder approved these changes
Looks good.

2024-01-17 14:12 UTC, merged