packaging: Add article on stack rebuilds
getsolus/help-center-docs pull request #559
Opened 2024-08-22 20:25 UTC by EbonJaeger

## Description

Add an article on doing stack rebuilds.

Resolves https://github.com/getsolus/help-center-docs/issues/489

Signed-off-by: Evan Maddock <maddock.evan@vivaldi.net>

2024-09-01 18:08 UTC, TraceyC77 requested changes
Overall this is really well laid out and clarifies quite a few things. I had some minor suggestions for readability.

2024-09-01 18:08 UTC, TraceyC77 commented on docs/packaging/stack-rebuilds.md
> +
Maybe have a note about rebasing (cover in the pull request doc) since that's something stack rebasing frequently runs into?

2024-10-23 17:07 UTC, EbonJaeger commented on docs/packaging/stack-rebuilds.md
> +When the developers of a library release a new update, they may decide to bump the `.so` version, and code symbols are added and/or removed from the library. If a library is updated, and the `.so` ve
Reworded slightly. How does it look now?

2024-10-24 01:50 UTC, TraceyC77 commented on docs/packaging/stack-rebuilds.md
> +When the developers of a library release a new update, they may decide to bump the `.so` version, and code symbols are added and/or removed from the library. If a library is updated, and the `.so` ve
Looks good!

2024-10-24 01:50 UTC, TraceyC77 approved these changes
Looks good.

2024-10-24 01:57 UTC, merged